<?php

/**
 * @file
 * farmOS forest management module.
 */

include_once 'farm_forest.features.inc';

/**
 * Implements hook_help().
 */
function farm_forest_help($path, $arg) {

  // Add help text to the forest plan list page.
  if ($path == 'farm/plans/forest') {
    $help = '<p>' . t("This page lists all forest plans. Select one from the list below to view it, or click \"Add forest plan\" to create a new one.") . '</p>';
    $help .= '<p>' . t("Plans can be archived for future reference. To view archived plans, use the \"Filter/sort\" options in the list below.") . '</p>';
    return $help;
  }

  // If the path starts with 'farm/plan/%', then load the plan and see if it is
  // a forest plan. If not, bail. Otherwise continue.
  if (strpos($path, 'farm/plan/%') === 0) {
    $plan = farm_plan_load($arg[2]);
    if (empty($plan) || $plan->type != 'forest') {
      return '';
    }
  }

  // Add help text to all farm/plan/% paths.
  switch ($path) {

    // Plan add/edit form.
    case 'farm/plan/add/forest':
    case 'farm/plan/%/edit':
      $help = '<p>' . t('Use the form below to configure the settings for this forest plan.') . '</p>';
      return $help;

    // Plan view page.
    case 'farm/plan/%':
    case 'farm/plan/%/view':
      $help = '<p>' . t('This page summarizes the details of this forest plan.') . '</p>';
      $help .= '<p>' . t('To edit the plan, click the "Settings" tab.') . '</p>';
      return $help;
  }
}

/**
 * Implements hook_farm_ui_entities().
 */
function farm_forest_farm_ui_entities() {
  return array(
    'farm_plan' => array(
      'forest' => array(
        'label' => t('Forest Plan'),
        'label_plural' => t('Forest Plans'),
        'view' => 'farm_forest_plan',
      ),
    ),
  );
}
